### PR TITLE
add a way to build image in container

### PR DESCRIPTION
**Pull request by wlfl**
This PR adds a way to build the image in a container (either podman or docker).

### CODE REVIEW

**Comment by birkb** [comment]
Thanks for the work! Let me test it on macOS...

**Comment by wlfl** [comment]
An issue comes up if the build directory is not inside of the project directory (e.g. project dir is ~/src/iksdp_desktop but build dir is ~/build). In this case another mount is needed as the resulting iso would not be accessible.

**Comment by Joe-Public** [comment]
I tested it with docker on my linux host. In general it works good but I have a few ideas for improvement:

I get a warning when I run `debian-live/container-build.sh -b`:
```
1 warning found (use docker --debug to expand):
- InvalidDefaultArgInFrom: Default value for ARG debian:${debian_version}-slim results in empty or invalid base image name (line 3)
```
Defining a default value, like e.g. `debian_version=undefined` in Containerfile.template prevents the warning.

When answering the question to use an apt caching proxy with yes, although none is available, the image will build without an error. But of course the packages "curl sudo ca-certificates jq" will not get installed. So the image won't work. Maybe there is some way to check if the proxy is really available. Also some advice on how to install a proxy could be helpful (maybe even providing or pointing to a container file). But in general the proxy is not too important, if you keep the build directory (see next idea) and so also the package cache for the majority of the packages.

Maybe it is possible to add an option to configure a directory which is added as an additional volume and mapped to the configured build directory. As you already commented, when I ran the the container (`debian-live/container-build.sh -r`) the ISO file was built, but deleted immediately afterwards :). Usually (at least) I don't want to mix the build directory into the project directory. Also changing the `BUILD_DIR` in build.sh to e.g. `/iksdp_desktop/build` will always be shown as a change of build.sh in git (as long as we don't change the default value there).

**But as it works in general I think we could also merge the changes in the current state.** Any ideas from the others?

**Comment by birkb** [comment]
I have added macOS support (https://github.com/batchworksde/iksdp_desktop/pull/34/commits/8cf392720e2c8803aae653d5d50713ff357d0a8e) for the script. Please check if that still works on your Linux variants...

**Comment by birkb** [comment]
> Usually (at least) I don't want to mix the build directory into the project directory. Also changing the BUILD_DIR in build.sh to e.g. /iksdp_desktop/build will always be shown as a change of build.sh in git (as long as we don't change the default value there).

I opt for a `build` or `.build` that should contain all files/folders generated by the script. This folder should be added to the .gitignore file...

**Comment by birkb** [comment]
> Maybe it is possible to add an option to configure a directory which is added as an additional volume and mapped to the configured build directory. 

Yes, currently the generated image is lost because of https://github.com/batchworksde/iksdp_desktop/blob/8cf392720e2c8803aae653d5d50713ff357d0a8e/debian-live/container-build.sh#L108

The volume is a good idea because it avoids an additional copy step. It would also keep the `lb` cache for further builds...

**Comment by wlfl** [comment]
> I opt for a `build` or `.build` that should contain all files/folders generated by the script. This folder should be added to the .gitignore file...

I agree.

If we create the build directory in the project root there would be no need for an additional volume.

**Review by birkb — APPROVED** [review]
lgtm

**Pull request merged**
